// =============================================================================
// File: WarehousePOAttributeValuePOFactory.java
// Generated by JGen Code Generator from INTERSHOP Communications AG.
// Generator template: ORMFactory.xpt(checksum: 6e6bf2256972a853c83260dcdcdafcb3)
// =============================================================================
// The JGen Code Generator software is the property of INTERSHOP Communications AG. 
// Any rights to use are granted under the license agreement. 
// =============================================================================
package bc_warehouse_orm;

import com.intershop.beehive.core.capi.common.Factory;
import com.intershop.beehive.orm.capi.common.FindMode;
import com.intershop.beehive.orm.capi.description.ClassDescription;
import com.intershop.beehive.orm.capi.engine.ORMEngine;

/**
 * This class provides life cycle management methods for the class WarehousePOAttributeValuePO.
 *
 * @see bc_warehouse_orm.WarehousePOAttributeValuePO
 * @generated
 */
public class WarehousePOAttributeValuePOFactory extends Factory
{
    /**
     * The name which can be used to lookup a factory from the naming manager.
     * 
     * @deprecated use "NamingMgr.getInstance().lookupFactory(WarehousePOAttributeValuePO.class)" instead
     * @generated
     */
    @Deprecated
    public static final String FACTORY_NAME = "bc_warehouse_orm.WarehousePOAttributeValuePO";

    /**
     * The constructor.
     *
     * @generated
     */
    public WarehousePOAttributeValuePOFactory(ORMEngine engine, ClassDescription classDescription)
    {
        super(engine, classDescription);

        WarehousePOAttributeValuePO.ownerRelation = classDescription.getRelationDescription("owner");

    }

    /**
     * Creates a new instance of class WarehousePOAttributeValuePO.
     *
     * @return the new instance of class WarehousePOAttributeValuePO
     * @generated modifiable
     */
    public WarehousePOAttributeValuePO create(String name, String localeID, int type, WarehousePO owner)
    {

        String ownerID = owner.getUUID();

        WarehousePOAttributeValuePOKey key = new WarehousePOAttributeValuePOKey(ownerID, name, localeID);
        WarehousePOAttributeValuePO instance = (WarehousePOAttributeValuePO)getEngine().getPersistenceManager()
                                                                                       .createObject(key,
                                                                                                       getClassDescription());

        instance.setAttributeValue(WarehousePOAttributeValuePO.typeAttribute, Integer.valueOf(type));

        instance.setRelatedObject(WarehousePOAttributeValuePO.ownerRelation, owner);

        // {{ create
        // put your custom create code here
        // }} create

        return instance;
    }

    /**
     * Removes an object by its primary key.
     *
     * @generated
     */
    public void remove(WarehousePOAttributeValuePOKey key)
    {
        WarehousePOAttributeValuePO object = getObjectByPrimaryKey(key);
        if (object != null)
        {
            object.remove();
        }
    }

    /**
     * Locates an instance of class WarehousePOAttributeValuePO based on its primary key.
     *
     * @param key the primary key to use for lookup
     * @return the object for the specified primary key or null, if it wasn't found
     * @generated
     */
    public WarehousePOAttributeValuePO getObjectByPrimaryKey(WarehousePOAttributeValuePOKey key)
    {
        return (WarehousePOAttributeValuePO)super.getObjectByPrimaryKeyObject(key);
    }

    /**
     * Locates an instance of class WarehousePOAttributeValuePO based on its primary key.
     *
     * @param key the primary key to use for lookup
     * @param mode the strategy to use for the lookup
     * @return the object for the specified primary key or null, if it wasn't found
     * @generated
     */
    public WarehousePOAttributeValuePO getObjectByPrimaryKey(WarehousePOAttributeValuePOKey key, FindMode mode)
    {
        return (WarehousePOAttributeValuePO)super.getObjectByPrimaryKeyObject(key, mode);
    }

}
